### ISSUE TITLE
Excuse me

### ISSUE THREAD

**Issue by sssssh** [zamansky/using-emacs#2]
I start my emacs (nested in terminal, different with you video's) after download you emacs's config, the log show some bugs.

Warning (initialization): An error occurred while loading ‘/Users/noodle/.emacs.d/init.el’
- in my .emacs.d finder also have init.el, myinit.el, myinit.org ...
 
File error: Cannot open load file, No such file or directory, ob-shell
- what's the ob-shell, it means ob-shell.el, i really don't kown.

**Comment by kenzo44** [comment]
What operating system are you using?

**Comment by zamansky** [comment]
I'm using the latest Linux Mint and Emacs 26.0.50 built from source. I just recloned the repo and built fresh and everything worked on my system.

ob-shell is something related to org-mode but I haven't seen that error.

There are times when I've had to load Emacs a couple of times to get the full installation to work (not this time though).

You might want to see if you already have an older version of org-mode installed or an older version of Emacs with an older version of org-mode.

**Comment by sssssh** [comment]
GNU Emacs 25.3.1 built from homebrew.

Start emacs everytime that showed: 
- Warning (initialization): An error occurred while loading ‘/Users/noodle/.emacs.d/init.el’:
- File error: Cannot open load file, No such file or directory, ob-shell
